### ISSUE TITLE
Reverted commit 90f2daf

### ISSUE THREAD

**Issue by nullbio** [markbates/refresh#18]
Hi Mark, is there a reason 90f2daf was reverted? Thanks.

**Comment by nullbio** [comment]
Revert here: https://github.com/markbates/refresh/commit/25435da78dbf2fa5067f3c156051103ad72bce0e

**Comment by markbates** [comment]
Yes; it was causing significant CPU usage. Reverting this commit brought CPU usage from 100+% to 0.3% on my machine. A lot of users complained about the increased CPU usage.

**Comment by nullbio** [comment]
You've reverted two commits, the one I'm referring to above seems unrelated to CPU usage. The CPU usage commit you reverted is here: https://github.com/markbates/refresh/commit/0b2bb8035576fb5fffcee9eed3233be1abdc9098

**Comment by markbates** [comment]
That commit needed to be reverted twice due do a bad merge.

-----------
Mark Bates

**Comment by nullbio** [comment]
This is somewhat confusing, because you've removed two different features and one is unrelated to CPU usage. Even if it needed to be reverted twice you definitely reverted two separate pieces of code. 

Just to clarify again, this is the commit I'm referring to which was merged a while ago: https://github.com/markbates/refresh/commit/90f2daf12da08f62255f309ece774fa94604a20f which has now seemingly mistakenly been reverted since it has nothing to do with CPU usage.

The one that seems intentionally reverted is here: https://github.com/markbates/refresh/commit/0b2bb8035576fb5fffcee9eed3233be1abdc9098 which has a commit message that refers to huge CPU usage.

**Comment by nullbio** [comment]
Hey @markbates not sure if you saw my reply. Just trying to get this sorted as quick as possible.

**Comment by markbates** [comment]
I have. I'm at GopherCon and have been very busy. Sorry. I will try and sort this out tomorrow.

**Comment by markbates** [comment]
@nullbio ok, it's back in there. sorry about that.

**Comment by nullbio** [comment]
@markbates Thank you Mark.
