### ISSUE TITLE
Avoid refreshing when _test.go file was updated

### ISSUE THREAD

**Issue by paganotoni** [markbates/refresh#27]
I've seen refresh rebuilds the app even when the files i'm changing are test files. I don't know if this should be a default but at least it would be good to have an option to avoid recompiling when _test.go changed.

Some of the ideas that come into my mind here are:
- Make by default not to recompile when `_test.go` changed
- Add an option like ignore_tests in the config
- Allow to specify _test.go as an excluded extension

**Comment by paganotoni** [comment]
@markbates I'm thinking to prepare a PR that allows to define `ignored_sufixes` in the YML, does this sounds good to you ?.

**Comment by paganotoni** [comment]
@markbates  ^

**Comment by occamist** [comment]
is there progress on this one? I might be able to have a look ignored_suffixes is not done right? there is ignored folders
