### ISSUE TITLE
Example of programmatic usage

### ISSUE THREAD

**Issue by v1rtl** [markbates/refresh#37]
I would like to use this module in [go-web-app](https://github.com/talentlessguy/go-web-app) but I don't know how to use this module in go code. @markbates, could you please give a small example? Also would be nice to put it in README :cat:

**Comment by markbates** [comment]
https://github.com/gobuffalo/buffalo/blob/master/buffalo/cmd/dev.go


PRs, especially for docs, are always welcome!

**Comment by v1rtl** [comment]
> https://github.com/gobuffalo/buffalo/blob/master/buffalo/cmd/dev.go
> 
> PRs, especially for docs, are always welcome!

The example you sent me uses a modification of the package cos this one only has `.Version` property (I didn't look at the code). Could you give a more clear example please?

![image](https://user-images.githubusercontent.com/35937217/63653965-df6f5b80-c77c-11e9-8668-cd872769d7ad.png)

**Comment by markbates** [comment]
That is the best example. If you read the entire thing you will see that there are more than one package imported. The GoDoc for these packages is very helpful to read as it might answer your questions.

**Comment by v1rtl** [comment]
> That is the best example. If you read the entire thing you will see that there are more than one package imported. The GoDoc for these packages is very helpful to read as it might answer your questions.

Sorry for my stupidity but I can't find any comments and examples in GoDoc. What does `NewWithContext` do in your code and what ctx should be? I'm a lil confused :(

![image](https://user-images.githubusercontent.com/35937217/63654037-aa173d80-c77d-11e9-837b-28bf05aead6b.png)
