### ISSUE TITLE
Problem with the refresh command

### ISSUE THREAD

**Issue by Evgenii-Gorbushin** [markbates/refresh#45]
Hello,

After the application was installed
**$ go get github.com/markbates/refresh**

I typed
**$ refresh init**

and I got the following issue
**bash: refresh: command not found...**

How could the issue be solved?
Thank you in advance :)

**Comment by reyhanfahlevi** [comment]
have you created it when go mod is enabled? try this:

```
~$ GO111MODULE=off go get -u github.com/markbates/refresh
```

**Comment by pollyduan** [comment]
By default, the refresh command is installed in the ~/go/bin directory. Make sure the directory is in the PATH environment variable.

~/go/bin/refresh init

**Comment by dcrystalj** [comment]
hm this is not working for me in docker
