### ISSUE TITLE
Signal killed error logging encapsulates additional line

### ISSUE THREAD

**Issue by nullbio** [markbates/refresh#7]
Just wondering what your output looks like? I'm getting this: http://imgur.com/a/OklSR

As you can see, the `signal: killed` error output is also including another output that wraps to another line (due to the `%s\n%s` instead of just `%s`). This messes up the color output as you can see, but it's also including a line that should not be there (note the closing === after the INFO line). The INFO log line is a result of calling zap's Info logging in my app, and unless I'm mistaken that doesn't log to Stderr -- so I'm not quite sure why it's being picked up by the os.Stderr stream as a part of this terminal output. As you can see it's also outputting the same line twice, once for the error and another for the other stream input I presume (os.Stdout?).

I can get expected output by changing this: https://github.com/markbates/refresh/blob/master/refresh/runner.go#L47

To just `return err` -- but I'm not sure if that works properly for all scenarios -- for example if my app did output something to Stderr then I suppose it would never be output to the terminal? So I think we need to do something like this instead, to stop the output from looking strange, but also include any potentially missing stderr information:

```
	if err != nil {
		m.Logger.Error(stderr.String())
		return err
	}
```

As for why those INFO lines are getting logged to Stderr I'm not sure, do you have any ideas here?

**Comment by nullbio** [comment]
Update: Seems this is a symptom of the fact that Zap's logger logs to Stderr regardless of what you're logging. Not really sure what can be done about this, then. Do you have any thoughts?

**Comment by nullbio** [comment]
After additional thought, I'm closing this issue. Refresh makes an assumption that your stderr stream is only for errors. I think it's a fair one. The problem is because zap uses Stderr for regular output, which I think isn't ideal. Instead we'll force it to use Stdout. Thanks.

**Comment by markbates** [comment]
Cool. You should consider a PR to them to have them use STDERR for what it was meant for.
